### ISSUE TITLE
Increase Data Capacity

### ISSUE THREAD

**Issue by DonaldTsang** [bloq/paperback#1]
The real-deal Paperback by Ollydbg actually packs a lot of data compared to yours, maybe instead of baking your own you can actually make a Javascript port of his software?

**Comment by jgarzik** [comment]
> The real-deal Paperback by Ollydbg actually packs a lot of data compared to yours, maybe instead of baking your own you can actually make a Javascript port of his software?

@DonaldTsang  I tried a number of tests of that software, and it did not work reliably with cryptographic key material.

**Comment by DonaldTsang** [comment]
@jgarzik but that software is used for general data storage, not just cryptographic keys, so IDK what is wrong with your case.

**Comment by jgarzik** [comment]
> @jgarzik but that software is used for general data storage, not just cryptographic keys, so IDK what is wrong with your case.

@DonaldTsang Certainly cryptographic data is a subset of 'data'   Nonetheless, "real Paperback" did not survive extensive testing, so I had to write my own.   My sneaking suspicion is that, like many backup softwares, little effort has been put into the "restore" side of the equation.

**Comment by DonaldTsang** [comment]
If I were to allow myself to speak up, I would hope that Paperback and Optar (another similar project) can be maintained as restore-easy while still being able to pack as much data from arbitrary files as possible.

**Comment by DonaldTsang** [comment]
Also check https://github.com/colorsafe/colorsafe if possible, since this is very recent and I think this can be replicated when compared to Paperback or Optar
